# Generated by Django 5.0.1 on 2024-01-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.FileField(blank=True, upload_to="project_images/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="technology",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
